// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8rZRY_r5W1t9bmitHCAWrf5GnomAkwo',
    appId: '1:771913597271:web:29be7bcb94200128b17e12',
    messagingSenderId: '771913597271',
    projectId: 'qr-attendence-3fe50',
    authDomain: 'qr-attendence-3fe50.firebaseapp.com',
    storageBucket: 'qr-attendence-3fe50.firebasestorage.app',
    measurementId: 'G-MYSXRRGBR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbriVE15xqPzpMdAYyXWEAa5lRayk3-w4',
    appId: '1:771913597271:android:8aaaebf53e05fa92b17e12',
    messagingSenderId: '771913597271',
    projectId: 'qr-attendence-3fe50',
    storageBucket: 'qr-attendence-3fe50.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYbwDkl6mhhhRU2BeedELZcNlXEDIiDnQ',
    appId: '1:771913597271:ios:6818602ec990eabfb17e12',
    messagingSenderId: '771913597271',
    projectId: 'qr-attendence-3fe50',
    storageBucket: 'qr-attendence-3fe50.firebasestorage.app',
    iosBundleId: 'com.dartnexuslab.smartroll',
  );
}
